  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: backend
  spec:
    selector:
      matchLabels:
        app: backend
    template:
      metadata:
        labels:
          app: backend
      spec:
        containers:
        - name: backend
          image: ghcr.io/emiliekilde/simple-fortune-cookie-backend:latest
          ports:
          - containerPort: 8080
          env:
            - name: REDIS_DNS
              value: "redis-service"
  
