  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: redis
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: redis
    template:
      metadata:
        labels:
          app: redis
      spec:
        containers:
          - name: redis
            image: redis:7-alpine
            volumeMounts:
              - name: redis
                mountPath: /data
            ports:
              - containerPort: 6379
        volumes:
          - name: redis
            emptyDir: {}
---
  apiVersion: v1
  kind: Service
  metadata:
    name: redis-service
  spec:
    type: LoadBalancer
    ports:
      - port: 80
        targetPort: 6379
    selector:
      app: redis
