name: Main workflow
on: push
jobs:
  build: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4   
      - name: setup go
        uses: actions/setup-go@v5
      - name: Build
        run: go build ./...
        
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4   
      - name: setup go
        uses: actions/setup-go@v5
      - name: Build
        run: go build ./...
      - name: Test frontend
        run: go test ./main_test.go

  
      
    
