name: Main workflow
on: push
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - name: Build go-build
        run: go build
      - name: run backend
        run: backend
      - name: run frontend
        run: frontend
      
    
